### ISSUE TITLE
Bug in ProUpRegTxPayload, scriptPayout reversed, inputsHash not always reversed

### ISSUE THREAD

**Issue by BenjaminNitschke** [dashpay/dashcore-lib#110]
For some reason the scriptPayout in https://github.com/dashevo/dashcore-lib/blob/master/lib/transaction/payload/proupregtxpayload.js gets reversed
`
ProUpRegTxPayload.fromBuffer = function (rawPayload) {
[...]
  var scriptPayoutSize = payloadBufferReader.readVarintNum();
  payload.scriptPayout = payloadBufferReader.read(scriptPayoutSize).reverse().toString('hex');
`

All other instances of scriptPayout, scriptOutputPayout, etc. are not reversed and ok:
https://github.com/dashevo/dashcore-lib/blob/master/lib/transaction/payload/proregtxpayload.js
https://github.com/dashevo/dashcore-lib/blob/master/lib/transaction/payload/proupservtxpayload.js

The test uses a reversed script hash as well:
https://github.com/dashevo/dashcore-lib/blob/master/test/transaction/payload/proupregtxpayload.js
should be:
  scriptPayout: '76a914f25c59be48ee1c4fd3733ecf56f440659f1d6c5088ac',

The inputsHash is also strange, it gets reversed in proupregtxpayload.js and proupservtxpayload.js, but not in proregtxpayload.js and prouprevtxpayload.js (plus the tests are adjusted to make them pass). This makes no sense to me, it should always be reversed to match what uint256 is doing, i.e. little endian encoding. E.g. proTXHash is always reversed and matches how uint256 works.

I also checked https://github.com/dashpay/docs/raw/master/binary/merchants/Integration-Resources-Dash-v0.13.0-Transaction-Types.pdf and the examples provided there won't work with reverse on scripts and non-reverse on inputsHash.

Here are plenty of examples based on the useful tests from here I just wrote for NBitcoin (not pushed upstream yet): 
https://github.com/DeltaEngine/NBitcoin/blob/master/NBitcoin.Tests/DashTests.cs
and the basic implementation (not as complete as dashcore-lib or cpp, but works):
https://github.com/DeltaEngine/NBitcoin/blob/master/NBitcoin.Altcoins/Dash.cs

Could provide a fix to dashcore-lib if you don't want to copy+paste my fixes ..
Also quickly checked the dashpay/dash repo and for example inputsHash is always just loaded this way: READWRITE(inputsHash);

**Comment by antouhou** [comment]
Hey @BenjaminNitschke !

I've checked the code of that payload, and it appears that this isn't the only issue in the payload JSON format. I'll create a fix in the nearest future and let you know when it's ready.

**Comment by nmarley** [comment]
Thanks for the report! Fixed as mentioned above, closing.
