### ISSUE TITLE
not published as bitcore-lib-dash on bower

### ISSUE THREAD

**Issue by coolaj86** [dashpay/dashcore-lib#12]
This is not published on bower.

**Comment by coolaj86** [comment]
Who knows if it'll work without having had necessary preprocessors run but... it's published on bower now!

```bash
bower register bitcore-lib-dash https://github.com/dashevo/bitcore-lib-dash.git
```

**Comment by Alex-Werner** [comment]
Thank you, I will look onto bower to be honest I didn't thought it was used and didn't gave it a proper maintain :x
