### ISSUE TITLE
payloadSigSize is incorrect for ProRegTxPayload

### ISSUE THREAD

**Issue by paddyquinn** [dashpay/dashcore-lib#120]
At [this line](https://github.com/dashevo/dashcore-lib/blob/master/lib/transaction/payload/proregtxpayload.js#L65) if `payloadSig` is present, `payloadSigSize` is set to `BLS_SIGNATURE_SIZE`. However, the payload is signed with the key that corresponds to the collateral outpoint, which can definitely be a non-BLS key. In fact, I am not sure it is possible for this collateral key to be a BLS key at all.

**Comment by nmarley** [comment]
That's a good point @paddyquinn . Does this attribute really even need to exist? Can't this be calculated with something like something like `options.payloadSig.length` ?

**Comment by paddyquinn** [comment]
I don't think this needs to exist. It isn't even used when [serializing](https://github.com/dashevo/dashcore-lib/blob/master/lib/transaction/payload/proregtxpayload.js#L215). It is used in the [toJSON](https://github.com/dashevo/dashcore-lib/blob/master/lib/transaction/payload/proregtxpayload.js#L180) call but that can easily be replaced.

**Comment by nmarley** [comment]
Hey @antouhou @Cofresi , would either of you be able to chime in one this one?

**Comment by antouhou** [comment]
@nmarley @paddyquinn Thank you for the report! Fixed in #121
