### ISSUE TITLE
Superblock Candidates not supported in govobject types

### ISSUE THREAD

**Issue by jhodges10** [dashpay/dashcore-lib#126]
When attempting to use dashcore-lib to parse a "trigger" object, `type: 2`, the library spits back an error about unsupported types. 

It would be great if the library just supported this type.

I may try to tackle this.

**Comment by nmarley** [comment]
Thanks for reporting! I do remember coming across this too, and I _think_ I even remember working on it, but can't find it anywhere right now.

**Comment by jhodges10** [comment]
@nmarley do you think anyone would have time to work on it this week?

**Comment by nmarley** [comment]
@jhodges10 Probably not _this_ week, we are having a workshop this week. Although it is a relatively trivial addition. Is this critical for you?

**Comment by jhodges10** [comment]
@nmarley It's not that critical since it only really comes up once a month and we just missed this month's superblock candidate.

I'm seeing if we can have someone tackle it on our end.

**Comment by nmarley** [comment]
@jhodges10 This should get close: https://github.com/dashevo/dashcore-lib/compare/master...dashevo:trigger?expand=1

I still need to add tests and test it (just hacked this together w/o testing this morning), but wanted to let you know so you wouldn't have to spend resources / double work on this.

**Comment by jhodges10** [comment]
@nmarley awesome!

You definitely made more progress than I would have in the same time. I'll keep an eye on this space, with the hopes that we can get it into the next Nexus release planned for the latter half of the month.

**Comment by nmarley** [comment]
Should be working well enough here: https://github.com/dashevo/dashcore-lib/pull/128 . I think we can close this if / when that gets merged.
