### ISSUE TITLE
about dash testnet coin

### ISSUE THREAD

**Issue by Ark-Chen** [dashpay/dashcore-lib#127]
I want some dash testnet coins for testing.But I can't find the faucet.

Can you provide me with a faucet website?

or give me some testnet coins.My testnet addresss: yMJyv7THUv6nYGKmkvo7ZnMowiYfSarn21

thank you very much

**Comment by strophy** [comment]
Sent you 1001 tDash. A faucet is available here if you need more: http://faucet.test.dash.crowdnode.io/

**Comment by Ark-Chen** [comment]
Thank you @strophy .
