### ISSUE TITLE
Lodash security update

### ISSUE THREAD

**Issue by vladanm** [dashpay/dashcore-lib#131]
Snyk found big security vulnerability in Lodash 4.17.11

https://github.com/lodash/lodash/issues/4348
https://thehackernews.com/2019/07/lodash-prototype-pollution.html?m=1

Is it possible to upgrade all libs to patched Lodash version?

**Comment by jhodges10** [comment]
This was fixed in #133. Recommended closing @antouhou

**Comment by Alex-Werner** [comment]
Thanks @jhodges10 for the heads up. 
Closing.
