### ISSUE TITLE
How to broadcast the serialized transaction to Dash Official server

### ISSUE THREAD

**Issue by WataMalon** [dashpay/dashcore-lib#134]
Current version of dashcore-lib explained that we would have to send the Transaction after serialized through our own local service running dashcore-node.
[https://github.com/dashevo/dashcore-lib/blob/master/docs/transaction.md](url)
> Now, this could just be serialized to hexadecimal ASCII values (transaction.serialize()) and sent over to the dashd reference client.

I found this endpoint
[https://insight.dash.org/insight/tx/send](url)

My question is:
Is there any way to send the serialized transaction directly to Dash Official server?

**Comment by WataMalon** [comment]
I meant there is currently no description about how to broadcast the transaction from a local hosting to that endpoint.
I tried the following line but it doesn't work
```
dashcore.broadcast(tx, function(err, returnedTxId){
  if (err) { console.log(err); }
  else { console.log('Successul broadcast: ' + returnedTxId); }
});
```

I need a hint how to arrange an input, something like https://insight.dash.org/insight/tx/send/***Transaction.serialized()*** or https://insight.dash.org/insight/tx/send/?transaction=***Transaction.serialized()***
and send command

help plz,

**Comment by Alex-Werner** [comment]
Hi @WataMalone9, 

The endpoint `tx/send` as you guessed it, just requires it to send him a serialized transaction.
This can be obtain using either `transaction.toString()` or `transaction.serialize()`, `transaction` being a valid instance of Transaction. 

You will find in the API documentation : https://github.com/dashevo/insight-api#transaction-broadcasting 
That the endpoint is indeed `/tx/send` as a POST parameter expecting a `rawtx` field. From your example, you seems to do use GET verb and have named the params `transaction` which is the reason you are not able to broadcast it. 

Also, in documentation, discard /tx/sendix as transaction are instant by default now.

**Comment by WataMalone9** [comment]
Hi @Alex-Werner 
in Javascript:
`rawtx = transaction.serialize();`
in PHP:
```
    $rawtx = $_POST['rawtx'];
    $url = 'https://insight.dash.org/insight-api/tx/send/'.$rawtx;
    $ch=curl_init();
    curl_setopt($ch,CURLOPT_SSL_VERIFYPEER,true);
    curl_setopt($ch,CURLOPT_RETURNTRANSFER,true);
    curl_setopt($ch,CURLOPT_URL,$url);
    $ccc = curl_exec($ch);
    $json = json_decode($ccc, true);
    echo '<pre>'.var_dump($json).'</pre>';
```
the result I got:

> array(3) {
>   ["status"]=>
>   int(404)
>   ["url"]=>
>   string(474) "/insight-api/tx/send/030000000150a71314e8c9c780764a30c92fb233a1c2f57e614a180a39cc1b6d54128bb979010000006b483045022100ee06f677312cd7bd25bfdb48bbe815495b54b14023f242cad73512a2003976fd02207e3d62d5dd2d1370ac917a6103e043465b109d5de0af4fab25193becea59c59201210316239d39dcc4f3140bb0668011ad507187f7ea5557fe8b04dda833c063a64596ffffffff02e3210400000000001976a914c20237f72e6da7dc302b7c2c74dfa7ff6aa9db8d88acbbc3b000000000001976a9149fad445ca015fe1e2333e6ff1e12b274a362fe9088ac00000000?"
>   ["error"]=>
>   string(9) "Not found"
> }
did I do something wrong?

**Comment by WataMalon** [comment]
Hi @Alex-Werner
in Javascript:
`var rawtx = transaction.serialize();`
in PHP:
```
    $rawtx = $_POST['rawtx'];
    $url = 'https://insight.dash.org/insight-api/tx/send/'.$rawtx;
    $ch=curl_init();
    curl_setopt($ch,CURLOPT_SSL_VERIFYPEER,true);
    curl_setopt($ch,CURLOPT_RETURNTRANSFER,true);
    curl_setopt($ch,CURLOPT_URL,$url);
    $ccc = curl_exec($ch);
    $json = json_decode($ccc, true);
    echo '<pre>'.var_dump($json).'</pre>';
```
the result I got:

> array(3) {
> ["status"]=>
> int(404)
> ["url"]=>
> string(474) "/insight-api/tx/send/rawtx_transaction_serialize_hash"
> ["error"]=>
> string(9) "Not found"
> }

did I do something wrong?

**Comment by antouhou** [comment]
@WataMalone9 In your code, it looks like you're appending the transaction to the url, while it should be in the request body, under parameter name `rawtx`, as stated in the doc: https://github.com/dashevo/insight-api#standard-transaction

**Comment by WataMalon** [comment]
@antouhou, @Alex-Werner, @nmarley 
Thank you very much, you guys showed me how to solve my problem

**Comment by antouhou** [comment]
@WataMalone9 You're welcome! :slightly_smiling_face:
