### ISSUE TITLE
bitcore-lib-dash.min.js does not load in browser

### ISSUE THREAD

**Issue by coolaj86** [dashpay/dashcore-lib#14]
`bitcore-lib-dash.js` loads in a browser with `require('bitcore-lib-dash')`.

`bitcore-lib-dash.min.js` seems to have been minified with a bad minifier.

This process seems to result in a working copy, however:

```bash
npm install -g bower gulp uglify-js

git clone git@github.com:dashevo/bitcore-lib-dash.git
pushd bitcore-lib-dash
  npm install
  gulp browser
  uglifyjs bitcore-lib-dash.js > bitcore-lib-dash.min.js
popd
```

I'm able to load that and run code as expected:

```js
// just checking that this library doesn't default to a bad prng:
Math.random = function () { throw new Error("insecure"); };

// loading and testing
var bitcore = require('bitcore-lib-dash')
var privateKey = new bitcore.PrivateKey();
privateKey.toAddress().toString();
```

**Comment by Alex-Werner** [comment]
The prng test is clever =D 

Thank you for the report, the minified file is minified using uglify, so not sure of what bad minifier mean in this context, let me get back to you checking some stuff (like a diff between gitted/plain new minifying,..)

**Comment by coolaj86** [comment]
Notice that the unminified version defines `require` as an implicit global on the first line:

https://raw.githubusercontent.com/dashevo/bitcore-lib-dash/master/bitcore-lib-dash.js

Notice that the minified version does not define `require`:

https://raw.githubusercontent.com/dashevo/bitcore-lib-dash/master/bitcore-lib-dash.min.js

**Comment by Alex-Werner** [comment]
Should be fix in master (0.15.2)

**Comment by coolaj86** [comment]
I can confirm that it was fixed in ab3b46b4aff1caf4d3c7fa0452ce7b88f052d3c5 (Jan 29, 2018) and 1301449839e19022dcbc6e1bd492d908047817e4 (Feb 8, 2018), but it is broken again in master (d933ac9fb8aa4d3280f47a6a9eb2eb4415616aa5 Feb 19, 2018)

**Comment by Alex-Werner** [comment]
Hi @coolaj86, I'm sorry, for the issue.
You said it's broken again on d933ac9 Feb 19, 2018, however : 

https://github.com/dashevo/bitcore-lib-dash/blob/d933ac9fb8aa4d3280f47a6a9eb2eb4415616aa5/bitcore-lib-dash.js

https://github.com/dashevo/bitcore-lib-dash/blob/d933ac9fb8aa4d3280f47a6a9eb2eb4415616aa5/bitcore-lib-dash.min.js

Both seems to be defining require, would you help me double-checking in your side please ? What am I missing ?

**Comment by Alex-Werner** [comment]
#26 is merged, this should fix the issue, right now it's on `develop` you can monitor it here : 

https://github.com/dashevo/bitcore-lib-dash/pull/28 (v0.15.4)

We will update the documentation in the coming days to reflect the changes (you won't require anymore but access it as you would on any non-node library). 

Closing that for now, don't hesitate to re-open if you see the need to. 
Keeping at your disposal for any needs :)
