### ISSUE TITLE
Typescript issues with Transaction.id and new Transaction()

### ISSUE THREAD

**Issue by zquestz** [dashpay/dashcore-lib#147]
Unfortunately the typescript definitions don't allow `transaction.id` to work as the test https://github.com/dashevo/dashcore-lib/blob/master/test/transaction/transaction.js#L177 indicates it should.

If you could fix the typescript definition file it would be super useful. =)

If anyone needs a workaround, this works for me:

```
export async function txHash({
  signed_tx
}: TxHashInput): Promise<TxHashOutput> {
  const tx = new dashcore.Transaction(signed_tx)

  // All this madness because tx.id doesn't work in typescript.
  const littleEndianHashBuffer = tx._getHash()

  var hashBuffer = Buffer.allocUnsafe(littleEndianHashBuffer.length)

  for (var i = 0, j = littleEndianHashBuffer.length - 1; i <= j; ++i, --j) {
    hashBuffer[i] = littleEndianHashBuffer[j]
    hashBuffer[j] = littleEndianHashBuffer[i]
  }

  return {
    tx_hash: hashBuffer.toString("hex")
  };
}
```

In addition `new Transaction()` doesn't work either, as it needs the serialized arg passed in. This makes it difficult to build transactions when using typescript. A fix for this would also be fantastic.

**Comment by zquestz** [comment]
Note: there are many other typescript issues as well.

Script doesn't have `from` defined, plus `fromAddress` doesn't expect the address arg in the typescript definition...

**Comment by zquestz** [comment]
Also seeing issues with Output... `Output is not a constructor`

**Comment by Alex-Werner** [comment]
Hey @zquestz, 
We are aware of it, right now there is limited typing supports that you could use but we noticed some of them are missing (.id is not the only one right now, some of the added features are also missing). 
I will add this in the current sprint, and we will probably release in the next days, as it should be handled correctly there I think it make sense to prioritize this task. 

For Output, it's part of Transaction : 

```
const { Output } = Transaction;
```

In the meantime, you should be able to bypass compiler check with `// @ts-ignore`, it will suppress following line errors.

**Comment by zquestz** [comment]
Thank you, however:

`Property 'Input' does not exist on type 'typeof Transaction'.`
`Property 'Output' does not exist on type 'typeof Transaction'.`

**Comment by zquestz** [comment]
Actually this beast works...

```
  outputs.forEach(function(value, index, array) {
    const address = new dashcore.Address(value.address, dashNetwork({ network }))
    const script = new dashcore.Script(address)
    // @ts-ignore
    const output = new dashcore.Transaction.Output({
      satoshis: value.quantity,
      script: script,
    })

    console.log(output)

    tx.addOutput(output)
  })
```

**Comment by Alex-Werner** [comment]
I think this can now be closed :)
Do not hesitate to reopen if there is a missing part, while we did a thorought verification, there was a lot of file to look at, and any forgotten piece is always possible.
