### ISSUE TITLE
How to fork dashcore-lib, dashcore-p2p and to modify it to be used for another coin the same type dip0003 coin ?

### ISSUE THREAD

**Issue by SashaRomanov** [dashpay/dashcore-lib#179]
I wanted to fork dashcore-lib,  dashcore-p2p to connect to another dip0003 that doesn't have p2p or lib

after too many attempts it didn't connect at all

tried to change the addNetwork in networks.js
but still didn't work

**Comment by Alex-Werner** [comment]
Hi @SashaRomanov, 
Do you have any logs that could help me understanding the issue ?

**Comment by SashaRomanov** [comment]
@Alex-Werner I updated the question. is it possible to fork it to use it for another dip0003 ?

**Comment by SashaRomanov** [comment]
The value of "offset" is out of range. It must be >= 0 and <= 3537. Received 3668
