### ISSUE TITLE
Missing OpCode Constant

### ISSUE THREAD

**Issue by bappelt** [dashpay/dashcore-lib#204]
Opcode.js is missing constants for opcode OP_CHECKSEQUENCEVERIFY (178).

## Expected Behavior
Constants  OP_CHECKSEQUENCEVERIFY should be defined as  178 

## Current Behavior
Obsolete OP_NOP3 is defined with for opcodes 178

## Environment
* 0.18.15

**Comment by Alex-Werner** [comment]
Hello @bappelt, 

Thank you for the issue, this has indeed been forgotten. 

We gonna work on it to provide you support as soon as possible.

**Comment by Alex-Werner** [comment]
Closing this one as #216 is now merged. 

Thank you for raising this issue !
