### ISSUE TITLE
Latest commits break browser compatibility

### ISSUE THREAD

**Issue by coolaj86** [dashpay/dashcore-lib#22]
In ab3b46b4aff1caf4d3c7fa0452ce7b88f052d3c5 (Jan 29, 2018) and 1301449839e19022dcbc6e1bd492d908047817e4 (Feb 8, 2018) `bitcore-lib-dash.js` works in browsers just fine.

However, commits into master as of d933ac9fb8aa4d3280f47a6a9eb2eb4415616aa5 (Feb 19, 2018) seem to have broken browser compatibility.

In a browser it complains that the module `bitcore-lib-dash` cannot be found. I imagine it's due to either a name change of how the module is loaded or a change in the commonjs/requirejs/universal/es6 loader wrapper.

**Comment by Alex-Werner** [comment]
#26 is merged, this should fix the issue, right now it's on `develop` you can monitor it here : 

https://github.com/dashevo/bitcore-lib-dash/pull/28 (v0.15.4)

We will update the documentation in the coming days to reflect the changes (you won't require anymore but access it as you would on any non-node library). 

Closing that for now, don't hesitate to re-open if you see the need to. 
Keeping at your disposal for any needs :)
