### ISSUE TITLE
ReferenceError: PrivateKey is not defined

### ISSUE THREAD

**Issue by ah2020b** [dashpay/dashcore-lib#224]
const dashcore = require('@dashevo/dashcore-lib');

var privateKey = new PrivateKey();

I have runned npm install @dashevo/dashcore-lib

But a simple code follow the docs, generated:
ReferenceError: PrivateKey is not defined

Look entire internet to find the soluction, but not found.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop, server, or mobile):
* Link to your project:

**Comment by Alex-Werner** [comment]
Hi @ah2020b, 

Please do `const { PrivateKey } = require('@dashevo/dashcore-lib');` instead :) 

or 

```
const dashcore = require('@dashevo/dashcore-lib');
var privateKey = new dashcore.PrivateKey();
```

**Comment by ah2020b** [comment]
Thank you, I will.
