### ISSUE TITLE
Address has mismatched network type.

### ISSUE THREAD

**Issue by Divyesh-mi** [dashpay/dashcore-lib#24]
I had created address using 'testnet' and i also passed 'testnet' as network type but it returns 'Address has mismatched network type'

**Comment by antouhou** [comment]
Hello @DivyeshMindinventory! Can you provide the code that gives you this error?

**Comment by Divyesh-mi** [comment]
Here is the code:


fetch(App.locals.global.APIbaseURL+'addrs/ybo5PPrU26WqP7k0cTgjxPmGcAtkQZHmDMp/utxo').then(function(resp) {
                return resp.json();
            `}).then(function(utxos)` {
                if (utxos.length > 0)
                {
                    let balance = 0;
                    for (let i = 0; i < utxos.length; i++) {
                        balance += unit.fromSatoshis(parseInt(utxos[i]['satoshis'])).toSatoshis();
                    }
                    let transactionAmt = transObj.transferAmt + 10000;
                    if ((balance - transactionAmt) > 0) {
                        try {
                            let tx = dash.Transaction();
                            tx.from(utxos);
                            tx.to('yQzGisMD5RBEyeiLqfL9wg8EW2QyemdPzn', transObj.transferAmt);
                            tx.to('yZqqjp2cWaLad4TTBDN4BuNLHCk2w6mYym',10000);
                            tx.change('ybo5PPrU26WqP7k0cTgjxPmGcAtkQZHmDMp');
                            tx.fee(10000);
                            tx.sign('ff72c5d00388376d319807786987fb18e72b4b7003081a9ab6ed9b729fc9cd48');

                            if (tx.getSerializationError()) {
                                let error = tx.getSerializationError().message;
                                switch (error) {
                                    case 'Some inputs have not been fully signed':
                                        returnData.status = 10;
                                        returnData.detail = "Please check your private key";
                                        break;
                                    default:
                                        returnData.status = 20;
                                        returnData.detail = error;
                                }
                                resolve(returnData)
                            } else {
                                fetch(App.locals.global.APIbaseURL+'tx/send', {
                                    method: 'POST',
                                    headers:{ 'Accept': 'application/json','Content-Type': 'application/json'},
                                    body: JSON.stringify({"rawtx": tx.serialize()}) })
                                    .then(function(res) {
                                        return res.json();
                                    }).then(function(returnedTxId) {
                                        resolve(returnData)
                                }).catch(err => {
                                    returnData.status = 50;
                                    returnData.detail = err.message;
                                    resolve(returnData)
                                });
                            }
                        } catch (error) {
                            returnData.status = 50;
                            returnData.detail = error.message;
                            resolve(returnData)
                        }
                    } else {
                        returnData.status = 60;
                        returnData.detail = "You don't have enough Satoshis to cover the miner fee.";
                        resolve(returnData)
                    }
                } else {
                    returnData.status = 70;
                    returnData.detail = "You don't have enough Satoshis to cover the miner fee.";
                    resolve(returnData)
                }
            });

**Comment by antouhou** [comment]
@DivyeshMindinventory You have `0` symbol in address `ybo5PPrU26WqP7k0cTgjxPmGcAtkQZHmDMp` on position 15. The correct address is `ybo5PPrU26WqP7kcTgjxPmGcAtkQZHmDMp`

**Comment by Divyesh-mi** [comment]
@antouhou Actually address was pasted wrong here. I tried after removing the 0 from address, still same issue.

**Comment by saritvakrat** [comment]
@DivyeshMindinventory Have you managed to solve the issue? I encounter the same thing

**Comment by Divyesh-mi** [comment]
Yes @ActoMatics. In my case, dash address was wrong.
