### ISSUE TITLE
install on existing node

### ISSUE THREAD

**Issue by Big-Brother** [dashpay/dashcore-lib#25]
I have a server already running a fully synced version of dashd

how do I install this on the server **without** having to download, install and sync another version of dashd?

**Comment by Alex-Werner** [comment]
Hi @Big-Brother, 
I think you are talking about bitcore-node-dash, this repo won't download anything. 
Also, bitcore-node-dash won't download node anymore, for various reason, it would be better to force people to do the little extra work of managing their own node.

Closing this as this is not related to this repository.
