### ISSUE TITLE
Please fix documentation links from README.MD

### ISSUE THREAD

**Issue by fsanano** [dashpay/dashcore-lib#38]

**Comment by gaboesquivel** [comment]
I think broken links should be fixed in master. cherry pick perhaps. 
I'm closing #42 in favor of #40.

**Comment by nmarley** [comment]
We merge the `develop` branch into `master` with each release -- links should be fixed in develop.

**Comment by gaboesquivel** [comment]
Yeah, what I meant is that I think that for something simple like this that doesn't involve code a cherry pick won't hurt. As if it were a hot fix to the readme. Dunno. Just a suggestion :)

**Comment by nmarley** [comment]
Probably a good idea! Looks like there's only 1 PR difference between the two right now, so probably ok to just merge into `master` now.

**Comment by nmarley** [comment]
Ok, done -- `develop` & `master` on the same commit now (they needed a common ancestor commit for GitHub to more easily work out differences anyway). This issue should be resolved now.

@gaboesquivel Thanks for the suggestion!

**Comment by gaboesquivel** [comment]
👍
