### ISSUE TITLE
Dashify example documentation from Bitcoin version

### ISSUE THREAD

**Issue by nmarley** [dashpay/dashcore-lib#39]
Our examples in the documentation are still copied from Bitcoin, e.g. in `doc/examples.md`. We need to convert these to Dash values so that they are less confusing and demonstrate that this is a Dash library.

**Comment by anirudh-chhangani** [comment]
This is a absolute must, I was literally confused for a few seconds while looking at the examples, is there any timeline on this, if its just renaming from bitcoin->dash or a few changes in calls here and there, maybe I can help.

**Comment by jhodges10** [comment]
I took a relatively thorough look through the docs and it looks this is pretty well addressed now @nmarley, @anirudh-chhangani. 

Recommend closing.

**Comment by Alex-Werner** [comment]
Closing. Do not hesitate to reopen in case one thinks this has not been addressed.
