### ISSUE TITLE
How to estimate fee ?

### ISSUE THREAD

**Issue by fsanano** [dashpay/dashcore-lib#41]

**Comment by stoesky** [comment]
After you create a transaction, pass the string value of the transaction in this function.
Basically, you estimate to pay 1 satoshi per byte 

`
function calculateFee(transaction) {
  const SATOSHI_PER_BYTE = 1;
  const transactionBytes = transaction.toString().length / 2;
  return Math.ceil(transactionBytes * SATOSHI_PER_BYTE);
}
`

**Comment by NishidaRyu416** [comment]
You could use [coinselect](https://github.com/bitcoinjs/coinselect).That way, you can easily select proper UTXO for a transaction, also calculate fees. You may have to make some changes to the UTXO for the library though.
