### ISSUE TITLE
React-Native : Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by Alex-Werner** [dashpay/dashcore-lib#60]
Hi ! 

On React-Native, when using dashcore-lib (dependencies of wallet-library) and specifically on using this kind of code : 

``` 
 const tx = new Dashcore.Transaction();
tx.to(address, satoshis);
``` 

Will result on Script to be called, and in this one, to throw an error 

```
TypeError: Right-hand side of 'instanceof' is not callable
    at new Script (script.js:35)
    at new UnspentOutput (unspentoutput.js:46)
    at Transaction._fromNonP2SH (transaction.js:561)
    at Transaction.from (transaction.js:554)
    at transaction.js:540
    at arrayEach (lodash.js:537)
    at Function.forEach (lodash.js:9359)
    at Transaction.from (transaction.js:539)
```

With debbuger, I can confirm that Address is indeed undefined. (https://github.com/dashevo/dashcore-lib/blob/master/lib/script/script.js#L35). 

The fix that is proposed here : https://github.com/bitpay/bitcore-lib/issues/184 worked well for me in local, I suspect the problem to come from babel, but for now just opening this issue so we can start discussing / debugging / fixing the problem =D

**Comment by NishidaRyu416** [comment]
I think you first need to specify the parameter, in this case utxos for`from` because you are doing now is just sending a certain amount of dash to someone from no resource.

Moreover, the error massages seem to suggest that you’ve gotten to do that.

Hope this helps

**Comment by jhodges10** [comment]
@Alex-Werner I think it's safe to close this issue now if you figured it out?

**Comment by Alex-Werner** [comment]
@NishidaRyu416 Oh! Only replied with an heart, but to confirm, yes we found the issue (thank you!) and fixed it. 
Closing it, do not to re-open if this is an error someone face and requires a fix in the repo. (thx @jhodges10 )
