### ISSUE TITLE
GovObject - Proposal : We should reject start_epoch, end_epoch, payment_amount is NaN

### ISSUE THREAD

**Issue by Alex-Werner** [dashpay/dashcore-lib#7]
See it here : https://github.com/dashevo/proposal-generator/issues/25 
and also see it here : https://github.com/dashpay/dash/pull/1707 

Now, a invalid proposal (aka having string instead of number for the designated fields), will be rejected. 
We want to handle that in before in bitcore-lib-dash.

**Comment by chaeplin** [comment]
fyi : 
12.2 has ```gobject check <data-hex>```. Can check a proposal without collateral submitting.

**Comment by Alex-Werner** [comment]
Merged in https://github.com/dashevo/bitcore-lib-dash/pull/8

**Comment by nmarley** [comment]
@Alex-Werner Are we able to close this now?
