### ISSUE TITLE
Filtering transactions of an address given the minBlockSize up untill the latest block?

### ISSUE THREAD

**Issue by anirudh-chhangani** [dashpay/dashcore-lib#83]
is there a way I can retrieve successful payment transactions for a given address in a given block range?

**Comment by antouhou** [comment]
Hi @anirudh-chhangani! `dashcore-lib` is just a library for manipulating consensus data, you can't retrieve any data using this library. If you want to retrieve something from the chain, you need [dashd-rpc](https://github.com/dashevo/dashd-rpc) client and a running instance of `dashd` on your machine. You need to download all transactions using `listSinceBlock` command, and then filter the list by the desirable address.

**Comment by anirudh-chhangani** [comment]
Ah, thanks!

**Comment by anirudh-chhangani** [comment]
Although, Not sure if its evident from readme(was not to me!) It would help to mention this distinction in the readme section. I actually thought this is all in one library to interact with public dash nodes. Also, if you don't mind answering it here, is there a necessity to run dashd locally, can't we connect to the public nodes? Thanks

**Comment by antouhou** [comment]
@anirudh-chhangani At the moment you have to run it on your own. In the future though, after dash 1.0 release, we will have a decentralized HTTP API which will be possible to use for such purposes.
